//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sln_SingleApartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Participant = new HashSet<Participant>();
        }
    
        public int ActivityID { get; set; }
        public int SubCategoryDetailID { get; set; }
        public string ActivityName { get; set; }
        public int PeopleCount { get; set; }
        public int MemberID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Step { get; set; }
        public string Note { get; set; }
        public string MeetingPoint { get; set; }
        public string Status { get; set; }
    
        public virtual ActivitySubCategory ActivitySubCategory { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participant { get; set; }
    }
}
