//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sln_SingleApartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int InformationID { get; set; }
        public System.DateTime InformationDate { get; set; }
        public int InformationCategoryID { get; set; }
        public Nullable<int> InformationSource { get; set; }
        public int DocumentID { get; set; }
        public string InformationContent { get; set; }
        public string Read_YN { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public int MemberID { get; set; }
        public Nullable<int> MemberCategoryID { get; set; }
    
        public virtual InformationCategory InformationCategory { get; set; }
        public virtual MemberInformationCategory MemberInformationCategory { get; set; }
        public virtual tMember tMember { get; set; }
    }
}
