//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sln_SingleApartment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SingleApartmentEntities : DbContext
    {
        public SingleApartmentEntities()
            : base("name=SingleApartmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityMainCategory> ActivityMainCategory { get; set; }
        public virtual DbSet<ActivitySubCategory> ActivitySubCategory { get; set; }
        public virtual DbSet<ActivitySubCategoryDetail> ActivitySubCategoryDetail { get; set; }
        public virtual DbSet<BuildCase> BuildCase { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Facility> Facility { get; set; }
        public virtual DbSet<FavoriteList> FavoriteList { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<InformationCategory> InformationCategory { get; set; }
        public virtual DbSet<InformationContent> InformationContent { get; set; }
        public virtual DbSet<Lease> Lease { get; set; }
        public virtual DbSet<MemberInformationCategory> MemberInformationCategory { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductMainCategory> ProductMainCategory { get; set; }
        public virtual DbSet<ProductPictures> ProductPictures { get; set; }
        public virtual DbSet<ProductSubCategory> ProductSubCategory { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomFacilities> RoomFacilities { get; set; }
        public virtual DbSet<RoomFavorite> RoomFavorite { get; set; }
        public virtual DbSet<RoomStyle> RoomStyle { get; set; }
        public virtual DbSet<tActivityCart> tActivityCart { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
    }
}
