//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sln_SingleApartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActivityCart
    {
        public int fJoinedId { get; set; }
        public Nullable<int> fMemberId { get; set; }
        public string fAvtivityName { get; set; }
        public Nullable<System.DateTime> fStartTime { get; set; }
        public Nullable<System.DateTime> fEndTime { get; set; }
        public string fLocation { get; set; }
        public Nullable<int> fPeopleCount { get; set; }
        public string fStatus { get; set; }
        public string fNote { get; set; }
    }
}
